name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '14'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '14.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0

      - name: Install deps
        run: pnpm install
        run: pnpm run build

      - name: copy dist file with scp
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 22
          ARGS: '-avzr --delete'
          SOURCE: './*'
          TARGET: ${{ secrets.REMOTE_TARGET }}
